#!/bin/bash

export LC_ALL="C"
set -euo pipefail

LIB_DIR="$(dirname "$(realpath "$0")")/../../lib"
. "$LIB_DIR/settings.sh"

RAWOUT=1
USAGE="

  Check status of the logged-in account"

. "$LIB_DIR/rest-lib.sh"

# works on /iam and /iam/ and /iam/check
rest_GET /iam
