#!/bin/bash

export LC_ALL="C"
set -euo pipefail

LIB_DIR="$(dirname "$(realpath "$0")")/../../lib"
. "$LIB_DIR/settings.sh"

USAGE="

  Lists all accounts"

. "$LIB_DIR/rest-lib.sh"

rest_GET /iam/accounts
