#!/bin/bash

export LC_ALL="C"
set -euo pipefail

LIB_DIR="$(dirname "$(realpath "$0")")/../../lib"
. "$LIB_DIR/settings.sh"

USAGE="CID

  Delete client CID

  POSITIONAL PARAMS
   CID       Unique client ID"

. "$LIB_DIR/rest-lib.sh"

(($# == 1)) || usage_exit

rest_DELETE /iam/clients/$1
