#!/bin/bash

export LC_ALL="C"
set -euo pipefail

LIB_DIR="$(dirname "$(realpath "$0")")/../../lib"
. "$LIB_DIR/settings.sh"

USAGE="[CID]

  Show client CID and its members or by default all clients."

. "$LIB_DIR/rest-lib.sh"

rest_GET /iam/clients${1:+/$1}
