#!/bin/bash

export LC_ALL="C"
set -euo pipefail

LIB_DIR="$(dirname "$(realpath "$0")")/../../lib"
. "$LIB_DIR/settings.sh"

USAGE="RID UID

  Remove member UID from role RID

  POSITIONAL PARAMS
   RID       Unique role ID (admins, users)
   UID       Unique account ID"

. "$LIB_DIR/rest-lib.sh"

(($# == 2)) || usage_exit

rest_DELETE /iam/roles/$1/$2
