#!/bin/bash

export LC_ALL="C"
set -euo pipefail

LIB_DIR="$(dirname "$(realpath "$0")")/../../lib"
. "$LIB_DIR/settings.sh"

USAGE="RID UID

  Add account UID to role RID

  POSITIONAL PARAMS
   RID       Unique role ID (admins or users)
   UID       Unique account ID"

. "$LIB_DIR/rest-lib.sh"

(($# == 2)) || usage_exit

echo "$2" | rest_POST /iam/roles/$1
