#!/bin/bash

. "$(dirname "$0")/common.sh"

(($# == 0)) || [ -n "${1%%-*}" ] || usage [CLIENT [TARGET [UNIQUE [PAYLOAD [FROM1 TILL1 ...]]]]]

NOW=$(date +%s)

CLIENT="${1:-CLIENT}"
TARGET="${2:-TARGET}"
UNIQUE="${3:-UN$$}"
PAYLOAD="${4:-DUMMY PAYLOAD}"
(($# > 6)) && shift 4 && SCHEDULE="$*" || SCHEDULE="$NOW $((NOW+10)) $((NOW+20)) $((NOW+30))"

exec "$(dirname "$0")/schedule-sms" "$CLIENT" "$TARGET" "$UNIQUE" "$PAYLOAD" $SCHEDULE
