#!/bin/bash

USAGE="[CLIENT [TARGET [KEY [SCHEDULE [MESSAGE]]]]]

  Schedule an SMS over Kafka, with dummy defaults.

  Refer to ../schedule-sms --help for argument details"

. "$(dirname "$0")/../../lib/common.sh"

[ -z "${1:-}" ] || [ -n "${1%%-*}" ] || usage_exit

NOW=$(date +%s)
CLIENT="${1:-test}"
TARGET="${2:-target1}"
KEY="${3:-kcat-dummy-$$}"
SCHEDULE="${4:-"$((NOW))-$((NOW+5));$((NOW+10))-$((NOW+15))"}"
MESSAGE="${5:-Dummy Kafka message}"

exec "$(dirname "$0")/../schedule-sms" "$CLIENT" "$TARGET" "$KEY" "$SCHEDULE" "$MESSAGE"
