#!/bin/bash

USAGE="CLIENT TARGET

  Block a target from receiving further SMS

  POSITIONAL PARAMS
   CLIENT    Client ID
   TARGET    Target ID assigned by client"

. "$(dirname "$0")/../lib/common.sh"

(($# == 2)) || usage_exit

CLIENT="$1"
TARGET="$2"

printf '{ "action": "block", "client": "%s", "target": "%s" }\n' "$CLIENT" "$TARGET" |
kcat_send
