#!/bin/bash

EVENTKEY="schedule"
USAGE="CLIENT TARGET BIZKEY SCHEDULE PAYLOAD

  Schedule an SMS over Kafka

  POSITIONAL PARAMS
   CLIENT       Client on whose behalf you are sending
   TARGET       Identifier of the target (recipient)
   BIZKEY       Client key for this send
   SCHEDULE     Schedule string
   PAYLOAD      Message to be scheduled

  The SCHEDULE can be either
     SEC-SEC(;SEC-SEC)* where SEC is epoch seconds (date +%s)
     ISO/ISO(;ISO/ISO)* where ISO is zoned datetime (date -Is)"

. "$(dirname "$0")/../lib/common.sh"

(($# == 5)) || usage_exit

CLIENT="$1"
TARGET="$2"
BIZKEY="$3"
SCHEDULE="$4"
PAYLOAD="$5"

printf '{ "client": "%s", "target": "%s", "key": "%s", "schedule": "%s", "message": "%s" }\n' \
	"$CLIENT" "$TARGET" "$BIZKEY" "$SCHEDULE" "$PAYLOAD" |
kcat_send
