#!/bin/bash

export LC_ALL="C"
set -euo pipefail

create_dummy() {
    ACC="$1"
    shift
    ../admin/account-create -dv $ACC $ACC $ACC $ACC "$@"
}

create_dummy nnn
create_dummy nnt test
create_dummy nan admins
create_dummy nat admins test
create_dummy unn users
create_dummy unt users test
create_dummy uan users admins
create_dummy uat users admins test
