#!/bin/bash

USAGE="CLIENT KEY

  Cancel a scheduled SMS

  POSITIONAL PARAMS
   CLIENT    Client ID
   KEY       Identifier assigned by client"

. "$(dirname "$0")/../lib/common.sh"

(($# == 2)) || usage_exit

CLIENT="$1"
KEY="$2"

printf '{ "action": "cancel", "client": "%s", "key": "%s" }\n' "$CLIENT" "$KEY" |
kcat_send
