#!/bin/bash

CONTEXT=/block
USAGE="CLIENT TARGET

  Block all scheduling to CLIENT's TARGET

  POSITIONAL PARAMS
   CLIENT         Unique client ID
   TARGET         Identifies SMS destination"

. "$(dirname "$0")/../lib/common.sh"

(($# == 2)) || usage_exit 1

echo | rest_PUT /$1/$2
