#!/bin/bash

CONTEXT=/schedule
USAGE="CLIENT yes-i-am-sure

  Remove all scheduled SMS for CLIENT.

  You need to add the 'yes-i-am-sure' because this is pretty
  destructive action.

  POSITIONAL PARAMS
   CLIENT         Unique client ID
   yes-i-am-sure  Literal required text"

. "$(dirname "$0")/../lib/common.sh"

(($# == 2)) && [ "$2" = 'yes-i-am-sure' ] || usage_exit 1

rest_DELETE /$1?confirm=$2
