#!/bin/bash

TOPIC='sms-status'
USAGE="CORREL STATUS ERRCODE ERRTEXT ...

  Fake a response from the SMS gateway

  POSITIONAL PARAMS
   CORREL   Correlation ID (the process instance ID)
   STATUS   Status to report back
   ERRCODE  Error code
   ERRTEXT  Error description"

. "$(dirname "$0")/../../lib/common.sh"

(($# >= 1)) || usage_exit

CORREL="$1"
STATUS="${2:-SENT}"
ERRCODE="${3:-0}"
(($# >= 4)) && shift 3 && ERRTEXT="$*" || ERRTEXT="No error"

printf '{ "correl-id": "%s", "sms-status": "%s", "error-code": %d, "error-text": "%s" }\n' \
	"$CORREL" "$STATUS" "$ERRCODE" "$ERRTEXT" |
kcat_send
