#!/bin/bash

export LC_ALL="C"
set -euo pipefail

LIB_DIR="$(dirname "$(realpath "$0")")/../lib"
. "$LIB_DIR/settings.sh"

RAWOUT=1
USAGE="[CLIENT]

  Return list of blocks for CLIENT [$CLIENT]"

. "$LIB_DIR/rest-lib.sh"

(($# == 1)) && CLIENT="$1" && shift || true
(($# == 0)) || usage_exit

rest_GET "/block/$CLIENT"
