#!/bin/bash

export LC_ALL="C"
set -euo pipefail

LIB_DIR="$(dirname "$(realpath "$0")")/../lib"
. "$LIB_DIR/settings.sh"

USAGE="CLIENT INSTANCE

  Cancel a scheduled send

  POSITIONAL PARAMS
   CLIENT    Client ID
   INSTANCE  Unique process instance identifier"

. "$LIB_DIR/rest-lib.sh"

(($# == 2)) || usage_exit 1

rest_DELETE /schedule/$1/by-id/$2
