#!/bin/bash

export LC_ALL="C"
set -euo pipefail

LIB_DIR="$(dirname "$(realpath "$0")")/../lib"
. "$LIB_DIR/settings.sh"

USAGE="[CLIENT] BATCH

  List scheduled processes for BATCH

  POSITIONAL PARAMETERS
    CLIENT  Client ID [$CLIENT]
    BATCH   Batch ID assigned by client [$BATCH]"

. "$LIB_DIR/rest-lib.sh"

(($# == 2)) && CLIENT="$1" && shift || true
(($# == 1)) && BATCH="$1" && shift || usage_exit

rest_GET "/schedule/$CLIENT/by-batch/$BATCH"
