#!/bin/bash
#
#  Command-line test client for sms-scheduler that submits over REST

export LC_ALL="C"
set -euo pipefail

# Source shared functions, default settings, and public keys for encryption
LIB_DIR="$(dirname "$(realpath "$0")")/../lib"
. "$LIB_DIR/settings.sh"

# The functions in kafka-lib.sh will display this
USAGE="[[[[[[[[[PUBFILE] CLIENT] BATCH] BIZKEY] TARGET] SCHEDULE] SENDER] RECIPIENT] FILE]

  Schedule an SMS over REST

  POSITIONAL PARAMS
   PUBFILE    Public key file to encrypt with [lib/keys/\${CLIENT}.pub]
   CLIENT     Client on whose behalf you are sending [$CLIENT]
   BATCH      Batch identifier for this (fake batch) send [$BATCH]
   BIZKEY     Client identifier for this specific send [\${CLIENT}-\${RANDOM}]
   TARGET     Client identifier for the recipient [encrock(\$RECIPIENT)]
   SCHEDULE   Sending schedule (see below) [+0]
   SENDER     Sender name or number [$SENDER]
   RECIPIENT  Destination number [$RECIPIENT]
   FILE       File with message body or '-' for stdin [-]

  SCHEDULE format is either
    SEC-SEC(;SEC-SEC)* where SEC is epoch seconds (date +%s)
    ISO/ISO(;ISO/ISO)* where ISO is zoned datetime (date -Is)
    +SEC1[+SEC2] between SEC1 and SEC2 (default 600) after now"

# Source the libraries
. "$LIB_DIR/rest-lib.sh"
. "$LIB_DIR/crypto-lib.sh"
. "$LIB_DIR/schedule-lib.sh"

# Parse the optional arguments
(( $# == 9 )) && PUBKEY="$1"    && shift || true
(( $# == 8 )) && CLIENT="$1"    && shift || true
(( $# == 7 )) && BATCH="$1"     && shift || true
(( $# == 6 )) && BIZKEY="$1"    && shift || true
(( $# == 5 )) && TARGET="$1"    && shift || true
(( $# == 4 )) && SCHEDULE="$1"  && shift || true
(( $# == 3 )) && SENDER="$1"    && shift || true
(( $# == 2 )) && RECIPIENT="$1" && shift || true
(( $# == 1 )) && FILE="$1"      && shift || FILE='-'

# Rewrite the SCHEDULE +SEC1[+SEC2] convenience to real input
[ "${SCHEDULE#+}" = "${SCHEDULE}" ] || SCHEDULE="$(rewrite_schedule "$SCHEDULE")"

# If TARGET is not set, make it the encrocked recipient
[ -n "${TARGET:-}" ] || TARGET="$(encrock_phone "${RECIPIENT: -9}")"

# Produce the encrypted payload for CLIENT
PAYLOAD="$(encrypted_sms "$PUBFILE" "$RECIPIENT" "$SENDER" "$FILE")" || err_exit "failed to produce encrypted SMS"

# Dump the standard diags
dump_diags
emit "PUBFILE   = $PUBFILE"
emit "CLIENT    = $CLIENT"
emit "BATCH     = $BATCH"
emit "BIZKEY    = $BIZKEY"
emit "TARGET    = $TARGET"
emit "SCHEDULE  = $SCHEDULE"
emit "SENDER    = $SENDER"
emit "RECIPIENT = $RECIPIENT"

# Produce the message and POST it on the CLIENT URL
printf '{ %s%s%s%s"payload": "%s" }' \
        "${BATCH:+\"batch\": \"$BATCH\", }" \
        "${BIZKEY:+\"key\": \"$BIZKEY\", }" \
        "${TARGET:+\"target\": \"$TARGET\", }" \
        "${SCHEDULE:+\"schedule\": \"$SCHEDULE\", }" \
	"$PAYLOAD" |
rest_POST /schedule/$CLIENT
