#!/bin/bash

export LC_ALL="C"
set -euo pipefail

CONTEXT=/block

# Source shared functions, default settings, and public keys for encryption
LIB_DIR="$(dirname "$(realpath "$0")")/../lib"
. "$LIB_DIR/settings.sh"

USAGE="CLIENT TARGET

  Block all scheduling to CLIENT's TARGET

  POSITIONAL PARAMS
   CLIENT         Unique client ID
   TARGET         Identifies SMS destination"

. "$LIB_DIR/rest-lib.sh"

(($# == 2)) || usage_exit 1

echo | rest_PUT /$1/$2
