#!/bin/bash

export LC_ALL="C"
set -euo pipefail

CONTEXT=/block
RAWOUT=1

# Source shared functions, default settings, and public keys for encryption
LIB_DIR="$(dirname "$(realpath "$0")")/../lib"
. "$LIB_DIR/settings.sh"

USAGE="CLIENT [TARGET]

  Return list of blocks for CLIENT, or check block for TARGET

  POSITIONAL PARAMS
   CLIENT    Client ID
   TARGET    Target ID"

. "$LIB_DIR/rest-lib.sh"

(($# >= 1)) && (($# <= 2)) && [ -n "${1%%-*}" ] || usage_exit 1

rest_GET "/$1${2:+/$2}"
