#!/bin/bash

export LC_ALL="C"
set -euo pipefail

CONTEXT=/schedule

# Source shared functions, default settings, and public keys for encryption
LIB_DIR="$(dirname "$(realpath "$0")")/../lib"
. "$LIB_DIR/settings.sh"

USAGE="CLIENT TARGET INST

  Cancel a scheduled send

  POSITIONAL PARAMS
   CLIENT    Unique client ID
   TARGET    Identifies the recipient
   INST      Identifies the send withing recipient"

. "$LIB_DIR/rest-lib.sh"

(($# == 3)) || usage_exit 1

rest_DELETE /$1/$2/$3
