#!/bin/bash

export LC_ALL="C"
set -euo pipefail

CONTEXT=/schedule

# Source shared functions, default settings, and public keys for encryption
LIB_DIR="$(dirname "$(realpath "$0")")/../lib"
. "$LIB_DIR/settings.sh"

USAGE="CLIENT yes-i-am-sure

  Remove all scheduled SMS for CLIENT.

  You need to add the 'yes-i-am-sure' because this is pretty
  destructive action.

  POSITIONAL PARAMS
   CLIENT         Unique client ID
   yes-i-am-sure  Literal required text"

. "$LIB_DIR/rest-lib.sh"

(($# == 2)) && [ "$2" = 'yes-i-am-sure' ] || usage_exit 1

rest_DELETE /$1?confirm=$2
