#!/bin/bash

export LC_ALL="C"
set -euo pipefail

LIB_DIR="$(dirname "$(realpath "$0")")/../lib"
. "$LIB_DIR/settings.sh"

USAGE="CLIENT TARGET

  Remove all scheduled SMS for TARGET in CLIENT

  POSITIONAL PARAMS
   CLIENT    Unique client ID
   TARGET    Identifier for recipient assigned by client"

. "$LIB_DIR/rest-lib.sh"

(($# == 2)) || usage_exit 1

rest_DELETE /schedule/$1/by-target/$2
