#!/bin/bash

export LC_ALL="C"
set -euo pipefail

LIB_DIR="$(dirname "$(realpath "$0")")/../lib"
. "$LIB_DIR/settings.sh"

USAGE="CLIENT yes-i-am-sure

  Remove all scheduled SMS for CLIENT.

  You need to add the 'yes-i-am-sure' because this can have pretty
  disastrous effects.

  POSITIONAL PARAMS
   CLIENT         Unique client ID
   yes-i-am-sure  Literal required text"

. "$LIB_DIR/rest-lib.sh"

(($# == 2)) && [ "$2" = 'yes-i-am-sure' ] || usage_exit

rest_DELETE /$1?confirm=$2
