#!/bin/bash
#
# Convenience script to call any REST method on any URL

export LC_ALL="C"
set -euo pipefail

LIB_DIR="$(dirname "$(realpath "$0")")/../lib"
. "$LIB_DIR/settings.sh"

RAWOUT=1
USAGE="[[VERB] URL]

  Perform any REST method on URL $BASEURL$CONTEXT[/URL]

  POSITIONAL PARAMETER
    VERB  REST verb [GET]
    URL   URL relative to $BASEURL$CONTEXT (see -b and -c)"

. "$LIB_DIR/rest-lib.sh"

(($# == 2)) && VERB="$1" && shift || true
(($# == 1)) && URL="$1"  && shift || true
(($# == 0)) || usage_exit

rest_${VERB:-GET} ${URL:+/$URL}
