#!/bin/bash

export LC_ALL="C"
set -euo pipefail

CONTEXT=/schedule

# Source shared functions, default settings, and public keys for encryption
LIB_DIR="$(dirname "$(realpath "$0")")/../lib"
. "$LIB_DIR/settings.sh"

USAGE="CLIENT ID

  Return process instance by ID

  POSITIONAL PARAMS
   CLIENT    Client ID
   INSTANCE  Unique ID"

. "$LIB_DIR/rest-lib.sh"

(($# == 2)) || [ -n "${1%%-*}" ] || usage_exit 1

rest_GET "/$1/by-id/$2"

