#!/bin/bash

export LC_ALL="C"
set -euo pipefail

LIB_DIR="$(dirname "$(realpath "$0")")/../lib"
. "$LIB_DIR/settings.sh"

USAGE="CID UID

  Remove account UID from client CID

  POSITIONAL PARAMS
   CID       Unique client ID
   UID       Unique account ID"

. "$LIB_DIR/rest-lib.sh"

(($# == 2)) || usage_exit

rest_DELETE /iam/clients/$1/$2
