#!/bin/bash

export LC_ALL="C"
set -euo pipefail

LIB_DIR="$(dirname "$(realpath "$0")")/../lib"
. "$LIB_DIR/settings.sh"

USAGE="[RID]

  Show role RID and its members or by default all roles."

. "$LIB_DIR/rest-lib.sh"

(($# <= 1)) || usage_exit

rest_GET /iam/roles${1:+/$1}
