#!/bin/bash

CONTEXT=/iam/accounts/
USAGE="ID

  Delete account ID"

. $(realpath $(dirname "$0")/../lib/common.sh)

(( $# == 1 )) || usage_exit 1

[ "$1" != "$UNAME" ] || err_exit "Hotel California Exception: you cannot delete yourself"

rest_DELETE $1
