#!/bin/bash

CONTEXT=/iam/clients
USAGE="CID

  Delete client CID

  POSITIONAL PARAMS
   CID       Unique client ID"

. "$(dirname "$0")/../lib/common.sh"

(($# == 1)) || usage_exit 1

rest_DELETE /$1
