#!/bin/bash

CONTEXT=/iam/roles
USAGE="GID UID

  Remove account UID from role GID

  POSITIONAL PARAMS
   GID       Unique role ID (admins, users)
   UID       Unique account ID"

. "$(dirname "$0")/../lib/common.sh"

(($# == 2)) || usage_exit 1

# Parse the standard attributes
rest_DELETE /$1/$2
