#!/bin/bash

CONTEXT=/block
TEXTONLY=1
USAGE="CLIENT [TARGET]

  Return list of blocks for CLIENT, or check block for TARGET

  POSITIONAL PARAMS
   CLIENT    Client ID
   TARGET    Target ID"

. "$(dirname "$0")/../lib/common.sh"

(($# >= 1)) && (($# <= 2)) && [ -n "${1%%-*}" ] || usage_exit 1

rest_GET "/$1${2:+/$2}"
