#!/bin/bash

CONTEXT=/schedule
USAGE="CLIENT ID

  Return process instance by ID

  POSITIONAL PARAMS
   CLIENT    Client ID
   INSTANCE  Unique ID"

. "$(dirname "$0")/../lib/common.sh"

(($# == 2)) || [ -n "${1%%-*}" ] || usage_exit 1

rest_GET "/$1/by-id/$2"

