#!/bin/bash

CONTEXT=/schedule
USAGE="CLIENT TARGET BIZKEY SCHEDULE PAYLOAD

  Schedule an SMS

  POSITIONAL PARAMS
   CLIENT       Client on whose behalf you are sending
   TARGET       Identifier of the target (recipient)
   BIZKEY       Business key of this send
   SCHEDULE     Schedule string
   PAYLOAD      Message to be scheduled

  The SCHEDULE can be either
     SEC-SEC(;SEC-SEC)* where SEC is epoch seconds (date +%s)
     ISO/ISO(;ISO/ISO)* where ISO is zoned datetime (date -Is)"

. "$(dirname "$0")/../lib/common.sh"

(($# == 5)) || usage_exit

CLIENT="$1"
TARGET="$2"
BIZKEY="$3"
SCHEDULE="$4"
PAYLOAD="$5"

printf '{ "targetId": "%s", "uniqueId": "%s", "schedule": "%s", "payload":  "%s" }' \
	"$TARGET" "$BIZKEY" "$SCHEDULE" "${PAYLOAD/\"/\\\"}" |
rest_POST /$CLIENT
