#!/bin/bash

CONTEXT=/schedule
USAGE="CLIENT TARGET BIZKEY PAYLOAD FROM1 TILL1 ...

  Schedule an SMS

  POSITIONAL PARAMS
   CLIENT       Client on whose behalf you are sending
   TARGET       Identifier of the target (recipient)
   BIZKEY       Business key of this send
   FROM1 TILL1  Time slot for sending (seconds in the epoch)
   ...          ... more time slots in which to send"

. "$(dirname "$0")/../lib/common.sh"

(($# >= 6)) || usage_exit

CLIENT="$1"
TARGET="$2"
BIZKEY="$3"
PAYLOAD="$4"
shift 4
SCHEDULE="$*"

printf '{ "targetId": "%s", "uniqueId": "%s", "schedule": "%s", "payload":  "%s" }' \
	"$TARGET" "$BIZKEY" "$SCHEDULE" "${PAYLOAD/\"/\\\"}" |
rest_POST /$CLIENT
