#!/bin/bash

export LC_ALL="C"
set -euo pipefail

. "$(dirname "$(realpath "$0")")/lib/defaults.sh"

USAGE="[CLIENT] BIZKEY

  Cancel a scheduled SMS

  POSITIONAL PARAMS
   CLIENT    Client ID [$CLIENT]
   BIZKEY    Identifier assigned by client"

. "$(dirname "$0")/lib/common.sh"

(($# == 1)) || (($# == 2)) || usage_exit

(($# == 2)) && CLIENT="$1" && shift || true
(($# == 1)) && BIZKEY="$1" && shift || true

printf '{ "action": "cancel", "client": "%s", "key": "%s" }\n' "$CLIENT" "$BIZKEY" |
kcat_send
