#!/bin/bash

export LC_ALL="C"
set -euo pipefail

LIB_DIR="$(dirname "$(realpath "$0")")/../lib"
. "$LIB_DIR/settings.sh"

USAGE="[ID]

  Display account details for the logged-on user or for account ID"

. "$LIB_DIR/rest-lib.sh"

rest_GET /iam/accounts/${1:-${UNAME}}
