#!/bin/bash

export LC_ALL="C"
set -euo pipefail

LIB_DIR="$(dirname "$(realpath "$0")")/../lib"
. "$LIB_DIR/settings.sh"

USAGE="[ID] PASSWORD

  Set password for account ID or for logged on user [$UNAME]

  POSITIONAL PARAMS
   ID        Unique account ID [$UNAME]
   PASSWORD  Password for the account"

. "$LIB_DIR/rest-lib.sh"

(($# == 2)) && ID="$1"   && shift || ID=${UNAME}
(($# == 1)) && PASS="$1" && shift || usage_exit 1

echo "$PASS" | rest_POST /iam/accounts/$ID/password
