#!/bin/bash

export LC_ALL="C"
set -euo pipefail

LIB_DIR="$(dirname "$(realpath "$0")")/../lib"
. "$LIB_DIR/settings.sh"

USAGE="[SUBKEY]

  Queries the actuator at $CONTEXT[/SUBKEY]"

. "$LIB_DIR/rest-lib.sh"

rest_GET "/actuator${1+/$1}"
