#!/bin/bash

export LC_ALL="C"
set -euo pipefail

LIB_DIR="$(dirname "$(realpath "$0")")/../lib"
. "$LIB_DIR/settings.sh"

USAGE="CID UID

  Add account UID to client CID

  POSITIONAL PARAMS
   CID       Unique client ID
   UID       Unique account ID"

. "$LIB_DIR/rest-lib.sh"

(($# == 2)) || usage_exit

echo $2 | rest_POST /iam/clients/$1
