#!/bin/bash

export LC_ALL="C"
set -euo pipefail

LIB_DIR="$(dirname "$(realpath "$0")")/../lib"
. "$LIB_DIR/settings.sh"

USAGE="CID

  Create a new client group with name CID"

. "$LIB_DIR/rest-lib.sh"

(($# == 1)) || usage_exit

echo "$1" | rest_POST /iam/clients
