#!/bin/bash

CONTEXT=/iam/accounts
USAGE="ID PASSWORD

  Create account ID with the given attributes

  POSITIONAL PARAMS
   ID        Unique account ID
   PASSWORD  Password for the account"

. "$(dirname "$0")/../lib/common.sh"

(($# == 2)) || usage_exit 1

# Parse the standard attributes
ID="$1" PASS="$2"

echo "$PASS" | rest_POST /$ID/password
