#!/bin/bash

CONTEXT=/iam/clients
USAGE="CID UID

  Remove account UID from client CID

  POSITIONAL PARAMS
   CID       Unique client ID
   UID       Unique account ID"

. "$(dirname "$0")/../lib/common.sh"

(($# == 2)) || usage_exit 1

rest_DELETE /$1/$2
