#!/bin/bash

CONTEXT=/iam/groups
USAGE="GID UID

  Remove account UID from group GID

  POSITIONAL PARAMS
   GID       Unique group ID
   UID       Unique account ID"

. "$(dirname "$0")/../lib/common.sh"

(($# == 2)) || usage_exit 1

# Parse the standard attributes
rest_DELETE /$1/$2
