#!/bin/bash

# Be prepared for default invocation with is plaintext
[ -n "${2-}" ] || TEXTONLY=1
CONTEXT=/iam
USAGE="VERB [URL]

  Perform any REST method on URL $CONTEXT[/URL]"

. $(realpath $(dirname "$0")/../lib/common.sh)

((1 <= $# && $# <= 2)) || usage_exit 1

rest_$1 ${2:+/$2}
