#!/bin/bash

CONTEXT=/iam/roles
USAGE="GID UID

  Add account UID to role GID

  POSITIONAL PARAMS
   GID       Unique role ID (admins or users)
   UID       Unique account ID"

. "$(dirname "$0")/../lib/common.sh"

(($# == 2)) || usage_exit 1

# Parse the standard attributes
echo "$2" | rest_POST /$1
